---
- name: Install NTP daemon
  community.general.opkg:
    name: ntpd
    state: present
  when: ntp_enabled

- name: Deploy NTP configuration
  ansible.builtin.template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    mode: '0644'
  when: ntp_enabled
  notify: Restart ntp

- name: Ensure NTP service is enabled and started
  ansible.builtin.service:
    name: ntpd
    enabled: true
    state: started
  when: ntp_enabled
