---
- name: Deploy DHCP/DNS config
  ansible.builtin.template:
    src: dhcp.j2
    dest: /etc/config/dhcp
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart dnsmasq
    - Restart odhcpd
