---
- name: Update opkg cache
  ansible.builtin.command: opkg update
  changed_when: false

- name: Install baseline packages
  community.general.opkg:
    name: "{{ opkg_packages }}"
    state: present
