---
dependency:
  name: shell
  command: /bin/true

driver:
  name: docker

platforms:
  - name: instance
    image: debian:12
    command: /usr/bin/sleep infinity
    pre_build_image: true

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../..
  lint: |
    set -e
    ansible-lint

verifier:
  name: ansible
