---
dependency:
  name: shell
  command: /bin/true
driver:
  name: default
platforms:
  - name: instance
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../..
  inventory:
    host_vars:
      instance:
        ansible_connection: local
        ansible_python_interpreter: /usr/bin/python3
verifier:
  name: ansible
