---
- name: Ensure /usr/local/bin exists
  ansible.builtin.file:
    path: /usr/local/bin
    state: directory
    mode: '0755'
  when: backup_enabled | bool

- name: Deploy backup script
  ansible.builtin.template:
    src: backup.sh.j2
    dest: /usr/local/bin/backup.sh
    owner: root
    group: root
    mode: '0755'
  when: backup_enabled | bool
  notify: Run backup

- name: Schedule backup
  ansible.builtin.cron:
    name: "Config backup"
    minute: "{{ backup_schedule.split()[0] }}"
    hour: "{{ backup_schedule.split()[1] }}"
    day: "{{ backup_schedule.split()[2] }}"
    month: "{{ backup_schedule.split()[3] }}"
    weekday: "{{ backup_schedule.split()[4] }}"
    job: "/usr/local/bin/backup.sh"
  when: backup_enabled | bool
