---
- name: Deploy minimal wireless config
  ansible.builtin.template:
    src: wireless.j2
    dest: /etc/config/wireless
    owner: root
    group: root
    mode: '0644'
  notify: Reload wireless
  when: wireless_config.enabled | default(false)
