all:
  children:
    openwrt:
      hosts:
        staging-router:
          ansible_host: 10.10.10.1
      vars:
        ansible_user: root
        ansible_become: false
        ansible_shell_type: sh
        ansible_python_interpreter: /usr/bin/python3
