all:
  children:
    openwrt:
      hosts:
        lab-router:
          ansible_host: 192.168.1.1
      vars:
        ansible_user: root
        ansible_become: false
        ansible_shell_type: sh
        ansible_python_interpreter: /usr/bin/python3
