---
all:
  children:
    openwrt:
      hosts:
        router1:
          ansible_host: 192.168.1.1
        # router2:
        #   ansible_host: 10.0.0.2
      vars:
        ansible_user: root
        ansible_become: false
        ansible_shell_type: sh
        ansible_python_interpreter: /usr/bin/python3
