---
name: Ansible CI

'on':
  push:
    paths:
      - '.github/**'
      - 'ansible.cfg'
      - 'requirements.yml'
      - '.pre-commit-config.yaml'
      - 'commitlint.config.js'
      - 'Makefile'
      - 'sops.yaml'
      - 'inventories/**'
      - 'group_vars/**'
      - 'playbooks/**'
      - 'roles/**'
      - 'imagebuilder/**'
      - 'scripts/**'
  pull_request:
    paths:
      - '.github/**'
      - 'ansible.cfg'
      - 'requirements.yml'
      - '.pre-commit-config.yaml'
      - 'commitlint.config.js'
      - 'Makefile'
      - 'sops.yaml'
      - 'inventories/**'
      - 'group_vars/**'
      - 'playbooks/**'
      - 'roles/**'
      - 'imagebuilder/**'
      - 'scripts/**'

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Commitlint
        uses: wagoid/commitlint-github-action@v5

      - name: Install ShellCheck
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck

      - name: ShellCheck build script
        run: shellcheck imagebuilder/build.sh

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: >-
            ${{ runner.os }}-pip-${{ hashFiles(
              'requirements.yml', '.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache Ansible collections
        uses: actions/cache@v4
        with:
          path: ~/.ansible
          key: >-
            ${{ runner.os }}-ansible-${{ hashFiles(
              'requirements.yml', '.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ runner.os }}-ansible-

      - name: Install Ansible + linters + pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install "ansible-core>=2.14,<2.17" ansible-lint yamllint \
          pre-commit docker
          ansible --version
          ansible-lint --version
          yamllint --version
          pre-commit --version

      - name: Install Ansible collections
        run: ansible-galaxy collection install -r requirements.yml
      - name: Run lint
        run: make lint

      - name: Trivy filesystem scan
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: fs
          scanners: vuln,config,secret
          exit-code: '1'
          ignore-unfixed: true
          severity: CRITICAL,HIGH

      - name: Run tests
        run: ENV=lab make test

  deploy:
    needs: lint-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [lab, staging, production]
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Deploy
        run: ENV=${{ matrix.env }} make deploy
