---
name: Ansible CI

'on':
  push:
  pull_request:

jobs:
  lint-and-syntax:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install ShellCheck and Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget shellcheck
          curl -sfL \
            https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh \
            | sudo sh -s -- -b /usr/local/bin

      - name: ShellCheck build script
        run: shellcheck imagebuilder/build.sh

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Ansible + linters + pre-commit
        run: |
          python -m pip install --upgrade pip
            pip install "ansible-core>=2.14,<2.17" ansible-lint yamllint \
              pre-commit molecule molecule-plugins
          ansible --version
          ansible-lint --version
          yamllint --version
          molecule --version
          pre-commit --version

      - name: Install Ansible collections
        run: ansible-galaxy collection install -r requirements.yml

      - name: Run pre-commit
        run: pre-commit run --all-files

      - name: Yamllint repository
        run: yamllint .

      - name: Lint playbooks/roles
        run: |
          ansible-lint -v

      - name: Run Molecule tests
        run: |
          for role in roles/*; do
            if [ -d "$role/molecule" ]; then
              (cd "$role" && molecule test)
            fi
          done

      - name: Syntax-check playbooks (production inventory)
        run: |
          ansible-playbook -i inventories/production/hosts.ini --syntax-check \
            playbooks/bootstrap.yml
          ansible-playbook -i inventories/production/hosts.ini --syntax-check \
            playbooks/site.yml
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: fs
          ignore-unfixed: true
          severity: HIGH,CRITICAL
          exit-code: '1'
