name: Ansible CI

on:
  push:
  pull_request:

jobs:
  lint-and-syntax:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install ShellCheck
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck

      - name: ShellCheck build script
        run: shellcheck imagebuilder/build.sh

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Ansible + ansible-lint
        run: |
          python -m pip install --upgrade pip
          pip install "ansible-core>=2.14,<2.17" ansible-lint
          ansible --version
          ansible-lint --version

      - name: Install Ansible collections
        run: ansible-galaxy collection install -r requirements.yml

      - name: Lint playbooks/roles
        run: |
          ansible-lint -v

      - name: Syntax-check playbooks (production inventory)
        run: |
          ansible-playbook -i inventories/production/hosts.ini --syntax-check playbooks/bootstrap.yml
          ansible-playbook -i inventories/production/hosts.ini --syntax-check playbooks/site.yml
