---
name: Docs CI

'on':
  push:
  pull_request:

jobs:
  docs:
    if: >-
      startsWith(github.event.head_commit.message, 'docs:') ||
      (github.event_name == 'pull_request' && startsWith(github.event.pull_request.title, 'docs:'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Commitlint
        uses: wagoid/commitlint-github-action@v5
      - name: Markdown lint
        uses: avto-dev/markdown-lint@v1
        with:
          args: '**/*.md'
          config: .markdownlint.yml
